name: workflow 1
on: push

jobs:
  omar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Welcome 
        run: |
          echo "Hello world"
          sudo apt update -y
          sudo apt install cowsay -y
          cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
          cat dragon.txt
          sleep 15

  readme:
    needs: omar 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Show README 
        run: |
          ls -ltrah
          cat README.md
          chmod +x ./script.sh
          ./script.sh
          sleep 15
