name: workflow 1
on: push


jobs:
    omar:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v4
            - name: Welcome 
              run: |
                echo "Hello world"
                sudo apt update -y
                sudo apt install cowsay -y
                cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
                cat dragon.txt

    readme:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout 
              uses: actions/checkout@v4
            - name: show read me
              run: |
                ls -ltrah
                cat README.md
                chmod +x script.sh
                /home/adawy/Dam-test/Dam-test/.github/script.sh